### ISSUE TITLE
rep command isn't supported

### ISSUE THREAD

**Issue by TheLX5** [TheLX5/AsarSyntaxHighlight-VSCode#1]
The command to repeat lines of code isn't working.

https://rpghacker.github.io/asar/manual/#rep

**Comment by Atari2** [comment]
This is nasty, as far as I'm aware, the only real way to distinguish the rep opcode from the rep asar instruction is to check if the number after `rep` starts with `#` . If it does, then that's a REP 65816 instruction, if it's any other kind of number or math operation, it's asar's thing.

**Comment by TheLX5** [comment]
A detection for the rep command could be done with `(rep)\s+\d` and probably would work if it's executed before the mnemonics grammar rules.
This is where the textmate implementation in VSCode comes handy since everything is done in a single pass from top to bottom; there are some things not grouped together in the asar language file in order to not have some highlight issues, like label references having the lowest priority over anything else to not treat asar's directives as label references.

**Comment by TheLX5** [comment]
Alternatively, hardcoding a positive lookahead searching for a # in the rep mnemonic and leaving the rep command alone would work fine as well. Or a negative lookahead in the rep command.

**Comment by TheLX5** [comment]
Added on https://github.com/TheLX5/AsarSyntaxHighlight-VSCode/commit/2c3370e3b0658336d8ee05868afd27518e34cf3c
